version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:Rental@2026Secure@db:5432/rental
      JWT_SECRET_KEY: rentalportal123
    depends_on:
      - db

  user-app:
    build: ./frontend/user-app
    ports:
      - "4200:80"

  admin-app:
    build: ./frontend/admin-app
    ports:
      - "4300:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: rental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rental@2026Secure
    ports:
      - "5432:5432"